### ISSUE TITLE
Preserve old history

### ISSUE THREAD

**Issue by chrysn** [andrewleech/PyWebDAV3#7]
When the project was first imported, the import was based on a pypy tar ball. The original history is still available at https://code.google.com/archive/p/pywebdav/source/default/source, albeit in hg, and would provide valuable insight into the history of the project ("Why was that variable introduced? Did it serve a purpose back than that is now lost, or did I just miss something?).

IMO, now (as the project is young and not many forks are out there) would be still a good time to rebase the project once onto the commit the tar ball was created  (I've imported it to https://github.com/chrysn-pull-requests/PyWebDAV3/tree/old-history-used from the downloads google code provides; they also have an "import to GitHub" button). There are some commits later in the original project (dropping pkg_resources) that could still be mergable as well (at https://github.com/chrysn-pull-requests/PyWebDAV3/tree/old-history-latest).

**Comment by andrewleech** [comment]
Nicely spotted on the .hg entry, I never noticed the original project was a mercurial checked into the google svn. I definitely prefer to preserve history where I can.  
Unfortunately the import to github button's don't work on google code any more, I've tried for other projects I've taken on in the past.

I've grafted your imported history onto the base of my repo. 
I decided to merge the rewritten tree onto my existing master rather than a force push replacement. Even though it makes my history a little cluttered, existing clones, tags, releases all still line up which I prefer.
